"""Enforce one role per user

Revision ID: 018a08c1eb59
Revises: 2844c501fc3e
Create Date: 2026-08-11 12:45:03.316969

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '018a08c1eb59'
down_revision = '2844c501fc3e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_roles', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_user_role'), type_='unique')
        batch_op.create_unique_constraint('uq_user_single_role', ['user_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_roles', schema=None) as batch_op:
        batch_op.drop_constraint('uq_user_single_role', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_user_role'), ['user_id', 'role_id'])

    # ### end Alembic commands ###
