"""Add per-user announcement dismissal state

Revision ID: e8e26c587360
Revises: 23c38dd99401
Create Date: 2026-10-07 00:51:16.335378

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8e26c587360'
down_revision = '23c38dd99401'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('announcement_user_states',
    sa.Column('announcement_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('dismissed_at', sa.DateTime(), nullable=True),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('public_id', sa.String(length=36), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['announcement_id'], ['announcements.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('announcement_id', 'user_id', name='uq_announcement_user_state')
    )
    with op.batch_alter_table('announcement_user_states', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_announcement_user_states_announcement_id'), ['announcement_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_announcement_user_states_public_id'), ['public_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_announcement_user_states_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('announcement_user_states', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_announcement_user_states_user_id'))
        batch_op.drop_index(batch_op.f('ix_announcement_user_states_public_id'))
        batch_op.drop_index(batch_op.f('ix_announcement_user_states_announcement_id'))

    op.drop_table('announcement_user_states')
    # ### end Alembic commands ###
